<a href="https://colab.research.google.com/github/Prathmesh234/ConvolutionalNeuralNetwork/blob/main/Deep_Learning_Sp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is a Neural Network?
House pricing prediction - Size x will be a feature and Price Y is what we get.
Multiple features  - size, bedrooms etc
ReLU - Rectified Linear Unit

Each neuron can respond to a specific feature. Every input feature is connected to the other one  - densely populated NN.


Supervised Learning  - Input , output based. Image classification - CNN. Audio - 1 dimension temporal sequence : RNN.

Structured and Unstructured Data  - Well defined vs audio/image - not well defined.



Scale drives the deep learning progress.Scale is also depending on the labeled data. Scale - Data + Computation + algorithms.

Eg - Going from Sigmoid -> ReLU : The plateau in the sigmoid does not help will resolving the gradient descent. However, ReLU did.



**Week 2**

Binary Classification -

Logistic Regression - Let us say we have an image with 64x64  - and we can take a feature vector of the image it will be 64x64x3(RBG) = 12288 - dimension of the vector. m - training examples (x1,y1), (x2,y2) .......

X = [x1,x2,......] - width : m, height - n
X : Rnxm. Y = R1xm
x.shape - finding the vector's shape

**logistic Regression **- y = sigmoied(x^T + b). (cannot be negative and there is a chance it could be 0)

sigmoid(x) = 1/1+e^-x. x is large - sigmoid - 1. x is small - sigmoid - 0.

Cost function - Loss function or the error function. MSE does not work as gradient descent cannot find a local minima.

We use -(ylogy_pred + (1-y)log(1-y_pred)). Loss_fn - single training example. Cost functn - sum of all the loss func throught out the entire training dataset.


**Logistic regression as a Neural Network - ** -
j(w) - functn you want to minimize. w:= (updating) w- alpha d J(w)/dw. Derivative. Akpha - learning rate.


Computation Graph - Backprop uses derivative of a computation graph.

dvar = dJ/dvar.

Implementing gradient descent for logistic regression.

Gradient Descent on m examples -

-> J = 0, dw1 = 0, dw2 = 0, db =0

for i to m:
 zi = wTxi + b
 ai = sig(zi)
 loss = -[L(a,y)]
 dzi = ai - yi
 dw1 += x1idzi....

 All you have to know - w1 = w1 - alphadw1, w2...., b...... This is backprop.


 Vectorization - Getting rid of the for loop as shown above.

In [ ]:
##vectorization

import numpy as np
a = np.array([1,2,3,4])
print(a)

##Just remember vectorized version runs almost 300x faster.

[1 2 3 4]


In [ ]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)

249980.55636429758


In [ ]:
import numpy as np
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.0,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.  135.   99.    0.9]]


In [ ]:
cal = A.sum(axis=0)
print(cal)
cal.shape
##as you can see cal becomes a single row matrix

[ 58.2 239.  155.4  76.9]


(4,)

In [ ]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)
##Above is broadcasting in matrix

[[96.21993127  0.          2.83140283 88.42652796]
 [ 2.06185567 43.51464435 33.46203346 10.40312094]
 [ 1.71821306 56.48535565 63.70656371  1.17035111]]


In [ ]:
A = np.random.randn(2,3)
A

array([[-0.17367706, -0.07673314,  0.50207158],
       [ 0.63504976,  0.62961927, -1.40765031]])

In [ ]:
B = np.array([100,100,100])
Z = A+B
Z

array([[ 99.82632294,  99.92326686, 100.50207158],
       [100.63504976, 100.62961927,  98.59234969]])

In [ ]:
A = np.random.rand(5,1)
print(A)
A = np.dot(A,A.T)
A

[[0.75061773]
 [0.97906083]
 [0.87029315]
 [0.61650434]
 [0.56736188]]


array([[0.56342698, 0.73490042, 0.65325747, 0.46275909, 0.42587189],
       [0.73490042, 0.9585601 , 0.85206994, 0.60359525, 0.55548179],
       [0.65325747, 0.85206994, 0.75741017, 0.53653951, 0.49377116],
       [0.46275909, 0.60359525, 0.53653951, 0.38007761, 0.34978106],
       [0.42587189, 0.55548179, 0.49377116, 0.34978106, 0.3218995 ]])

In [ ]:
a = np.array([[2,1],[1,3]])
a*a

array([[4, 1],
       [1, 9]])

In [ ]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)
a*b

array([[ 0.58147095, -0.26229982,  0.5287682 ],
       [-0.23181515, -0.03534474, -0.55557305],
       [-0.04832295,  0.71795989, -0.32910311]])

In [ ]:
a= np.array([[1,1], [1,-1]])
b= np.array([[2], [3]])
c = a+b
c


array([[3, 3],
       [4, 2]])

**Week 3**

Neural Network with one hidden layer. Input layer, hidden layer, output layer.

Like logistic regression, but it repeats multiple times.

For a neural network with one hidden layer,
we will have the following equation for the generic representation of the z'th term which will be sent into the activation sigmoid function.

zn[m] = wn[m]^T + bn[m] = sigmoid(zn[n])

As you can see here n = node number and m is equal to the hidden layer number.


**ACTIVATION FUNCTIONS**

sigmoid(z[i]) - sigmoid function
sigmoid func goes between 0 and 1.

g(z[i]) - tanh function. Values between -1 and 1. Good for hidden layers.

For binary classification we should use sigmoid as it should be between 0 and 1 only.

ReLU function

ReLU func is better than sigmoid for a simple reason. If the value of z[i] is too small then the slope will be very small too and acheiving gradient descent will be harder. ReLU only gives value of 0 or 1 so it is generally better as it activates more on non 0 values.

BUT WHY DO WE NEED A NON LINEAR ACTIVATION FUNCTION?

The NN will only output a linear activation and not get the non linear values it.

**GRADIENT DESCENT**

Sigmoid function = g(z) = 1/1+e^-z

z == 0
g(z) = 0.5

z == -1
g(z) = 1/4.... =

tanh funciton  = g(z) = e^z - e^-z/e^z + e^-z

z == large, g'(z) = 0

ReLU

g(z) = max(0,z)

Leaky ReLU

g(z) = max(0.01, z)

GRADIENT DESCENT

Compute preds after cost func
Compute the derivatives of the cost function.
Repeat this until the parameters converge to a local minima.

Backprop
dz[2] = A[2] - Y
dw[2] = 1/mdz[2]A[1]T
db[2] = sum of all the dz[2]

dz[1] = w[2]T dz[2] * g[2](z[1])

Initializing weights randomly and why it is important

We did it as 0 but we need to initialize it as random as possible. The hidden units will be computing the same exact function and they will be computing exactly the same function.

So if we dont do it random, two hidden layers will have the same performance as one.

Also we usually multiply the weights by a small number to keep it's value small so when we compute tanh or any other activation function, for a larger value it should activate.



**WEEK 4**

Deep L Neural Network

Only a single layer is basically logistic regression. Very shallow model.

Deep neural network - a lot more hidden layers than logistic regression.

L = Number of layers in the NN,
N^[L] = Number of units in layer L.
N[2] = 3 (2nd layer has 3 neurons)
N[0] = nx
a^[L] = activations in layer l = g^[L](z^[L])


Forward propogation in a deep network

x = z^[1] = W^[1]x + b[1]
a[1] = g[1](z[1]) - activations for layer 1

z[2] = w[2]a[1] + b[2]
a[2] = g[2](z[2]) ....

z[l] = w[l]a[l-1] + b[l]
a[l] = g[l](z[l])

Stacking all the vectors up.

Working through the dimensions

dimensions = (number of vectors/neurons in layer l, 1)
(3,1) = x(2,1) + b
x = (3,2), b = (3,1)

Basically the simplest equation is (this is for the dimensions of the weights)  - w[l] = (n[l],n[l-1])
b[l] = (n[l],1)

Dimension for the activation functions (like the product after the activation function)-

z[l],a[l] = (n[l],1).

Also, if l =0, (n[l],m), m is equal to the number of training examples

Why deep representation of neural network -

For image representation/ face recognition
1) First layer could check the orientation of the edges
2) Second could check the horizontal edges etc.
3) Could group the edges together to form different detections like eyes etc.
4) detect different faces.

Audio - one layer could check for low level features, second could check the basic units of sound (phonemes)

Simple -> ..... -> complext....

Circuit theory and deep learning  - less l deep layers .., then we need more hidden units for the layers for equal performance. Specifically, it has to be exponentially large.

 **Building blocks of neural networks**

 Check the image which in the saved section in the folder.










dz[l] = w[l+1]^T dz[l+1]*g[l]'(z^[l])

Summary

x -> relu -> relu -> sigmoid -> y^ -> L(y^,y) and then we do backprop
dw[1] db[1] <- dw[2] db[2] <- dw[3] db[3] = -y/a +(1-y)/1-a

**Hyperparameters vs  Parameters**

Parameters: W[1], b[1], W[2], b[2], W[3]...

Hyperparams are  - learning rate (alpha), iterations , hidden layer, choice of activation functions

Control the final value of the parameters.

Applied deep learning  - empirical process. Idea -> code -> experiment -> idea....

We will have to keep tweaking the hyperparams in order to see if the model is getting better.

Deep learning vs Human brain

Like the brain is an oversimplification.

# **Shape of the Neural Network**

Shape of W[l] is (n[l],n[l-1]) and shape of b[l] is (n[l],1)

